version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      STRAPI_TOKEN: ${STRAPI_TOKEN}
      STRAPI_PROTOCOL: ${STRAPI_PROTOCOL}
      STRAPI_HOST: ${STRAPI_HOST}
      STRAPI_PORT: ${STRAPI_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM}
      API_BACKEND: ${API_BACKEND}
    restart: unless-stopped
