import { getMessages, setRequestLocale } from 'next-intl/server';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { Playfair_Display, Lato } from 'next/font/google';
import { routing } from '@/src/i18n/routing';
import { notFound } from 'next/navigation';
import '@/src/app/[locale]/globals.css';
import type { Metadata } from 'next';

const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
  weight: ['400', '700', '900'],
});

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) return notFound();

  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale} className="bg-background text-text-primary">
      <body
        className={`${playfair.variable} ${lato.variable} antialiased font-lato bg-background text-text-primary`}
      >
        <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
